// OPEN DRAWER
export const OPEN_DRAWER="OPEN_DRAWER";
export const CLOSE_DRAWER="CLOSE_DRAWER";

//OPEN FORM EDIT PROJECT
export const OPEN_FORM_EDIT_PROJECT="OPEN_FORM_EDIT_PROJECT";

//OPEN FORM CREATE TASK
export const OPEN_FORM_CREATE_TASK="OPEN_FORM_CREATE_TASK";

//SUBMIT EDIT PROJECT
export const SET_SUBMIT_EDIT_PROJECT="SET_SUBMIT_EDIT_PROJECT";

//SUBMIT CREATE TASK
export const SET_SUBMIT_CREATE_TASK="SET_SUBMIT_CREATE_TASK"