// PROJECT CATEGORY
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";

// CREATE PROJECT
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";

//PROJECT LIST
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const GET_PROJECT_LIST_SAGA = "GET_PROJECT_LIST_SAGA";

//EDIT PROJECT
export const EDIT_PROJECT_LIST="EDIT_PROJECT_LIST";
export const EDIT_PROJECT_LIST_SAGA="EDIT_PROJECT_LIST_SAGA"

//DELETE PROJECT
export const DELETE_PROJECT_LIST="DELETE_PROJECT_LIST";
export const DELETE_PROJECT_LIST_SAGA="DELETE_PROJECT_LIST_SAGA";

//PROJECT DETAIL
export const GET_PROJECT_DETAIL="GET_PROJECT_DETAIL";
export const GET_PROJECT_DETAIL_SAGA="GET_PROJECT_DETAIL_SAGA";

//GET ALL PROJECT
export const GET_ALL_PROJECT="GET_ALL_PROJECT";
export const GET_ALL_PROJECT_SAGA="GET_ALL_PROJECT_SAGA";


