//CREATE TASK
export const CREATE_TASK="CREATE_TASK";
export const CREATE_TASK_SAGA="CREATE_TASK_SAGA";


//GET TASK DETAIL
export const GET_TASK_DETAIL="GET_TASK_DETAIL";
export const GET_TASK_DETAIL_SAGA="GET_TASK_DETAIL_SAGA";

//UPDATE STATUS TASK 
export const UPDATE_STATUS_TASK="UPDATE_STATUS_TASK";
export const UPDATE_STATUS_TASK_SAGA="UPDATE_STATUS_TASK_SAGA";

//CHANGE TASK MODEL
export const CHANGE_TASK_MODEL="CHANGE_TASK_MODEL";
export const CHANGE_TASK_MODEL_SAGA="CHANGE_TASK_MODEL_SAGA";

//CHANGE_ASSIGNESS
export const CHANGE_ASSIGNESS="CHANGE_ASSIGNESS";

//REMOVE_USER_ASSIGN
export const REMOVE_USER_ASSIGN="REMOVE_USER_ASSIGN";

//UPDATE TASK
export const UPDATE_TASK="UPDATE_TASK";
export const UPDATE_TASK_SAGA="UPDATE_TASK_SAGA";

//HANDLE CHANGE POST API
export const HANDLE_CHANGE_POST_API="HANDLE_CHANGE_POST_API";
export const HANDLE_CHANGE_POST_API_SAGA="HANDLE_CHANGE_POST_API_SAGA";

