/** @format */

//SIGNIN
export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNIN_SAGA = "USER_SIGNIN_SAGA";

export const USLOGIN = "USLOGIN";

//GET USER
export const GET_USER = "GET_USER";
export const GET_USER_SAGA = "GET_USER_SAGA";
export const GET_USER_SEARCH = "GET_USER_SEARCH";

//ADD USER
export const ADD_USER_PROJECT = "ADD_USER_PROJECT";
export const ADD_USER_PROJECT_SAGA = "ADD_USER_PROJECT_SAGA";
//REMOVE USER
export const REMOVE_USER_FROM_PROJECT = "REMOVE_USER_PROJECT";
export const REMOVE_USER_FROM_PROJECT_SAGA = "REMOVE_USER_PROJECT_SAGA";

//GET USER BY PROJECTID
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";
export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
